### PR TITLE
docs: add comment about timestamp format

### PR DESCRIPTION
**Pull request by ZaneDragonBorn**
I've added comments to lines 21-22 which inform the users of what timestamp format they should use.

Please describe the changes this PR makes and why it should be merged:

Status

-   [ ] Code changes have been tested.

Semantic versioning classification:

-   [ ] This PR changes the library's interface (methods or parameters added)
-   [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
-   [ ] This PR only includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by zaida04** [comment]
Your comments need to be in the format of `/** comment stuff here **\` above the line you’re commenting in order for the documentation tool to pick it up.

**Comment by ZaneDragonBorn** [comment]
Should be good now

**Review by zaida04 — APPROVED** [review]

**Comment by DaStormer** [comment]
If we're going to do this, we should do it for all instances (I'm a sucker for consistency 😆)

**Comment by ZaneDragonBorn** [comment]
Lol teamwork is the dreamwork

**Comment by zaida04** [comment]
That’s a pretty heavy lift PR and I don’t want to burden @ZaneDragonBorn with it. We can put it on the internal list.

**Pull request merged**
